# Generated by Django 5.0.6 on 2024-05-15 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('already_raised', models.BooleanField(default=False)),
                ('old_ticket_id', models.CharField(max_length=250)),
                ('status', models.IntegerField(choices=[(1, 'Not Solved'), (2, 'In Progress'), (3, 'Solved'), (4, 'Closed')])),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='complaints.category')),
            ],
        ),
    ]
